export const UnitMapping: Record<number, string> = {
  0x00: "Marine",
  0x01: "Ghost",
  0x02: "Vulture",
  0x03: "Goliath",
  0x04: "Goliath Turret",
  0x05: "Siege Tank (Tank Mode)",
  0x06: "Siege Tank Turret (Tank Mode)",
  0x07: "SCV",
  0x08: "Wraith",
  0x09: "Science Vessel",
  0x0a: "Gui Motang (Firebat)",
  0x0b: "Dropship",
  0x0c: "Battlecruiser",
  0x0d: "Spider Mine",
  0x0e: "Nuclear Missile",
  0x0f: "Terran Civilian",
  0x10: "Sarah Kerrigan (Ghost)",
  0x11: "Alan Schezar (Goliath)",
  0x12: "Alan Schezar Turret",
  0x13: "Jim Raynor (Vulture)",
  0x14: "Jim Raynor (Marine)",
  0x15: "Tom Kazansky (Wraith)",
  0x16: "Magellan (Science Vessel)",
  0x17: "Edmund Duke (Tank Mode)",
  0x18: "Edmund Duke Turret (Tank Mode)",
  0x19: "Edmund Duke (Siege Mode)",
  0x1a: "Edmund Duke Turret (Siege Mode)",
  0x1b: "Arcturus Mengsk (Battlecruiser)",
  0x1c: "Hyperion (Battlecruiser)",
  0x1d: "Norad II (Battlecruiser)",
  0x1e: "Terran Siege Tank (Siege Mode)",
  0x1f: "Siege Tank Turret (Siege Mode)",
  0x20: "Firebat",
  0x21: "Scanner Sweep",
  0x22: "Medic",
  0x23: "Larva",
  0x24: "Egg",
  0x25: "Zergling",
  0x26: "Hydralisk",
  0x27: "Ultralisk",
  0x29: "Drone",
  0x2a: "Overlord",
  0x2b: "Mutalisk",
  0x2c: "Guardian",
  0x2d: "Queen",
  0x2e: "Defiler",
  0x2f: "Scourge",
  0x30: "Torrasque (Ultralisk)",
  0x31: "Matriarch (Queen)",
  0x32: "Infested Terran",
  0x33: "Infested Kerrigan (Infested Terran)",
  0x34: "Unclean One (Defiler)",
  0x35: "Hunter Killer (Hydralisk)",
  0x36: "Devouring One (Zergling)",
  0x37: "Kukulza (Mutalisk)",
  0x38: "Kukulza (Guardian)",
  0x39: "Yggdrasill (Overlord)",
  0x3a: "Valkyrie",
  0x3b: "Mutalisk Cocoon",
  0x3c: "Corsair",
  0x3d: "Dark Templar",
  0x3e: "Devourer",
  0x3f: "Dark Archon",
  0x40: "Probe",
  0x41: "Zealot",
  0x42: "Dragoon",
  0x43: "High Templar",
  0x44: "Archon",
  0x45: "Shuttle",
  0x46: "Scout",
  0x47: "Arbiter",
  0x48: "Carrier",
  0x49: "Interceptor",
  0x4a: "Protoss Dark Templar (Hero)",
  0x4b: "Zeratul (Dark Templar)",
  0x4c: "Tassadar/Zeratul (Archon)",
  0x4d: "Fenix (Zealot)",
  0x4e: "Fenix (Dragoon)",
  0x4f: "Tassadar (Templar)",
  0x50: "Mojo (Scout)",
  0x51: "Warbringer (Reaver)",
  0x52: "Gantrithor (Carrier)",
  0x53: "Reaver",
  0x54: "Observer",
  0x55: "Scarab",
  0x56: "Danimoth (Arbiter)",
  0x57: "Aldaris (Templar)",
  0x58: "Artanis (Scout)",
  0x59: "Rhynadon (Badlands Critter)",
  0x5a: "Bengalaas (Jungle Critter)",
  0x5b: "Cargo Ship (Unused)",
  0x5c: "Mercenary Gunship (Unused)",
  0x5d: "Scantid (Desert Critter)",
  0x5e: "Kakaru (Twilight Critter)",
  0x5f: "Ragnasaur (Ashworld Critter)",
  0x60: "Ursadon (Ice World Critter)",
  0x61: "Lurker Egg",
  0x62: "Raszagal (Corsair)",
  0x63: "Samir Duran (Ghost)",
  0x64: "Alexei Stukov (Ghost)",
  0x65: "Map Revealer",
  0x66: "Gerard DuGalle (BattleCruiser)",
  0x67: "Lurker",
  0x68: "Infested Duran (Infested Terran)",
  0x69: "Disruption Web",
  0x6a: "Command Center",
  0x6b: "ComSat",
  0x6c: "Nuclear Silo",
  0x6d: "Supply Depot",
  0x6e: "Refinery",
  0x6f: "Barracks",
  0x70: "Academy",
  0x71: "Factory",
  0x72: "Starport",
  0x73: "Control Tower",
  0x74: "Science Facility",
  0x75: "Covert Ops",
  0x76: "Physics Lab",
  0x78: "Machine Shop",
  0x79: "Repair Bay (Unused)",
  0x7a: "Engineering Bay",
  0x7b: "Armory",
  0x7c: "Missile Turret",
  0x7d: "Bunker",
  0x7e: "Norad II (Crashed)",
  0x7f: "Ion Cannon",
  0x80: "Uraj Crystal",
  0x81: "Khalis Crystal",
  0x82: "Infested CC",
  0x83: "Hatchery",
  0x84: "Lair",
  0x85: "Hive",
  0x86: "Nydus Canal",
  0x87: "Hydralisk Den",
  0x88: "Defiler Mound",
  0x89: "Greater Spire",
  0x8a: "Queens Nest",
  0x8b: "Evolution Chamber",
  0x8c: "Ultralisk Cavern",
  0x8d: "Spire",
  0x8e: "Spawning Pool",
  0x8f: "Creep Colony",
  0x90: "Spore Colony",
  0x91: "Unused Zerg Building1",
  0x92: "Sunken Colony",
  0x93: "Zerg Overmind (With Shell)",
  0x94: "Overmind",
  0x95: "Extractor",
  0x96: "Mature Chrysalis",
  0x97: "Cerebrate",
  0x98: "Cerebrate Daggoth",
  0x99: "Unused Zerg Building2",
  0x9a: "Nexus",
  0x9b: "Robotics Facility",
  0x9c: "Pylon",
  0x9d: "Assimilator",
  0x9e: "Unused Protoss Building1",
  0x9f: "Observatory",
  0xa0: "Gateway",
  0xa1: "Unused Protoss Building2",
  0xa2: "Photon Cannon",
  0xa3: "Citadel of Adun",
  0xa4: "Cybernetics Core",
  0xa5: "Templar Archives",
  0xa6: "Forge",
  0xa7: "Stargate",
  0xa8: "Stasis Cell/Prison",
  0xa9: "Fleet Beacon",
  0xaa: "Arbiter Tribunal",
  0xab: "Robotics Support Bay",
  0xac: "Shield Battery",
  0xad: "Khaydarin Crystal Formation",
  0xae: "Protoss Temple",
  0xaf: "Xel'Naga Temple",
  0xb0: "Mineral Field (Type 1)",
  0xb1: "Mineral Field (Type 2)",
  0xb2: "Mineral Field (Type 3)",
  0xb3: "Cave (Unused)",
  0xb4: "Cave-in (Unused)",
  0xb5: "Cantina (Unused)",
  0xb6: "Mining Platform (Unused)",
  0xb7: "Independent Command Center (Unused)",
  0xb8: "Independent Starport (Unused)",
  0xb9: "Independent Jump Gate (Unused)",
  0xba: "Ruins (Unused)",
  0xbb: "Khaydarin Crystal Formation (Unused)",
  0xbc: "Vespene Geyser",
  0xbd: "Warp Gate",
  0xbe: "Psi Disrupter",
  0xbf: "Zerg Marker",
  0xc0: "Terran Marker",
  0xc1: "Protoss Marker",
  0xc2: "Zerg Beacon",
  0xc3: "Terran Beacon",
  0xc4: "Protoss Beacon",
  0xc5: "Zerg Flag Beacon",
  0xc6: "Terran Flag Beacon",
  0xc7: "Protoss Flag Beacon",
  0xc8: "Power Generator",
  0xc9: "Overmind Cocoon",
  0xca: "Dark Swarm",
  0xcb: "Floor Missile Trap",
  0xcc: "Floor Hatch (Unused)",
  0xcd: "Left Upper Level Door",
  0xce: "Right Upper Level Door",
  0xcf: "Left Pit Door",
  0xd0: "Right Pit Door",
  0xd1: "Floor Gun Trap",
  0xd2: "Left Wall Missile Trap",
  0xd3: "Left Wall Flame Trap",
  0xd4: "Right Wall Missile Trap",
  0xd5: "Right Wall Flame Trap",
  0xd6: "Start Location",
  0xd7: "Flag",
  0xd8: "Young Chrysalis",
  0xd9: "Psi Emitter",
  0xda: "Data Disc",
  0xdb: "Khaydarin Crystal",
  0xdc: "Mineral Cluster Type 1",
  0xdd: "Mineral Cluster Type 2",
  0xde: "Protoss Vespene Gas Orb Type 1",
  0xdf: "Protoss Vespene Gas Orb Type 2",
  0xe0: "Zerg Vespene Gas Sac Type 1",
  0xe1: "Zerg Vespene Gas Sac Type 2",
  0xe2: "Terran Vespene Gas Tank Type 1",
  0xe3: "Terran Vespene Gas Tank Type 2",
  0xe4: "None",
} as const;
